// '@' Player
// '!' Exit
// ' ' Empty
// '#' Enemy
// '^' Air
// Anything else will look up "objects" and then
//   default to a wall
module.exports = {
  name: "Your Biggest Fan",
  data: [
    '0                                     0',
    '0                                     0',
    '0                                     0',
    '0                                     0',
    '0                                     0',
    '0                                     0',
    '0                                     0',
    '0                                     0',
    '0                                     0',
    '0                                     0',
    '0                                     0',
    '0                                     0',
    '0                                     0',
    '0                                     0',
    '0 ^      ^    ^     ^     ^           0',
    '0 ^      ^    ^     ^     ^           0',
    '0 ^      ^    ^     ^     ^           0',
    '0 ^      ^    ^     ^     ^           0',
    '0 ^      ^    ^     ^     ^        !  0',
    '0 ^      ^    ^     ^     ^     0000000',
    '0 ^      0    0     0     0           0',
    '0 ^                                   0',
    '0 ^                                   0',
    '0 ^                                   0',
    '0 ^                                   0',
    '0000                   00             0',
    '0      00         0          c    ^   0',
    '0                           000   ^   0',
    '0           00                    ^   0',
    '0                                 ^   0',
    '0                                 ^   0',
    '0                                 ^   0',
    '0                                 ^   0',
    '0                                 ^   0',
    '0                                 ^   0',
    '0                                 ^   0',
    '0                                 ^   0',
    '0            ^    b               ^   0',
    '0            ^   000              ^   0',
    '0            ^              00    ^   0',
    '0            ^         00         00000',
    '0            ^                        0',
    '0            ^                        0',
    '0            ^                        0',
    '0            ^                        0',
    '0            ^                        0',
    '0            ^                        0',
    '0            ^                        0',
    '0            ^                        0',
    '0            ^                        0',
    '0            ^                        0',
    '0            ^                        0',
    '0            ^                        0',
    '0 @  a       ^                        0',
    '00000000    000                       0',
  ],
  objects: {
    a: "Console|Fans create air currents. Float in with your towel for a boost!",
    b: "Console|When you can't figure out where to go, try thinking vertically.",
    c: "Console|You can start and stop floating multiple times while in midair.",
  },
  next: 'tutorial5',
}