var c = {
  MAX_DELTA: 1/30,
  GRAVITY: 500,
  PLAYER_ACCELERATION: 1200,
  PLAYER_MAX_SPEED: 300,
  PLAYER_JUMP_HEIGHT: 100,
};

c.PLAYER_JUMP_SPEED = Math.sqrt(2 * c.GRAVITY * c.PLAYER_JUMP_HEIGHT);

module.exports = c;