var c = {
  MAX_DELTA: 1/30,
  GRAVITY: 900,
  PLAYER_ACCELERATION: 1200,
  PLAYER_MAX_SPEED: 300,
  PLAYER_JUMP_HEIGHT: 120,
  SCREEN_WIDTH: 800,
  SCREEN_HEIGHT: 600,
  PLAYER_MAX_HEALTH: 3,
  PLAYER_BOUNCE_SPEED_X: 700,
  PLAYER_BOUNCE_SPEED_Y: 200,
  PLAYER_HIT_TIMEOUT: 50,
  TILE_SIZE: 50,
};

c.PLAYER_JUMP_SPEED = Math.sqrt(2 * c.GRAVITY * c.PLAYER_JUMP_HEIGHT);

module.exports = c;